- name: Deploy nginx and test site
  hosts: webservers
  roles:
    - { role: install_packages, become: true }
    - { role: deploy_nginx, become: true }
    - { role: download_site }
    - { role: prometheus, become: true }
    - { role: node_exporter, become: true }
    - { role: grafana, become: true }
