---
  - name: Create node_exporter user
    user:
      name: node_exporter
      state: present
      shell: /bin/false
      system: no 
      createhome: no
    become_user: root
  - name: Download node exporter
    apt:  
      pkg:
        -  prometheus-node-exporter
  - name: Start prometheus-node-exporter
    systemd:
      state: started
      name: prometheus-node-exporter
      daemon_reload: yes
      enabled: yes
  - name: Copy file
    copy:
      src: ~/infrastructure/git_updated/TerraformAnsibleGroup1/ansible/playbooks/roles/node_exporter/files/prometheus2.yml
      dest: /etc/prometheus/prometheus.yml
  - name: Restart prometheus
    systemd:
      name: prometheus
      state: restarted