---
  - name: Create node_exporter user
    user:
      name: node_exporter
      state: present
      shell: /bin/false
      system: no 
      createhome: no
    become_user: root
  - name: Download node exporter
    apt:  
      pkg:
        -  prometheus-node-exporter
  - name: Restart prometheus
    systemd:
      name: prometheus
      state: restarted