---
  - name: Create prometheus user
    user: 
      name: prometheus
      state: present
      shell: /bin/false
      system: no 
      createhome: no
    become_user: root
  - name: Create directory
    file:
      path: "{{ item }}"
      state: directory
      owner: prometheus
      group: prometheus
    with_items: 
      - /etc/prometheus
      - /var/lib/prometheus
  - name: Download prometheus
    apt:  
      pkg:
        -  prometheus
  - name: Copy file
    copy:
      src: ~/infrastructure/git_updated/TerraformAnsibleGroup1/ansible/playbooks/roles/prometheus/files/prometheus.yml
      dest: /etc/prometheus/prometheus.yml
  - name: Change file permission
    file:
      path: /etc/prometheus/prometheus.yml
      owner: prometheus
      group: prometheus
  - name: alert config file
    copy:
      src: ~/infrastructure/git_updated/TerraformAnsibleGroup1/ansible/playbooks/roles/prometheus/files/alert.rules.yml
      dest: /etc/prometheus/alert.rules.yml
  - name: Start prometheus
    systemd:
      state: started
      name: prometheus
      daemon_reload: yes
      enabled: yes