---
  - name: Create prometheus user
    user: 
      name: prometheus
      state: present
      shell: /bin/false
      system: no 
      createhome: no
    become_user: root
  - name: Create directory
    file:
      path: "{{ item }}"
      state: directory
      owner: prometheus
      group: prometheus
    with_items: 
      - /etc/prometheus
      - /var/lib/prometheus
  - name: Download prometheus
    apt:  
      pkg:
        -  prometheus
  - name: Start prometheus
    systemd:
      state: started
      name: prometheus
      daemon_reload: yes
      enabled: yes