- name: Update Ubuntu distro
  apt:
    upgrade: "yes"
    update_cache: yes
  when: ansible_distribution == 'Ubuntu'
  become: true
  tags:
    - skip_ansible_lint

- name: Install Packages
  package:
    name: "{{ packagesToInstall }}"
    state: present
  become: true
